name = "Metrology"
version = "0.1.0"
defaultTargets = ["metrology"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Metrology"

[[lean_exe]]
name = "metrology"
root = "Main"
